name: Build and push Docker image using Cloud Native Buildpacks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: coursessor-380913
  REPO_NAME: coursessor-repo
  IMAGE_NAME: coursessor-image
  IMAGE_TAG: latest
  LOCATION: europe-west8
  SERVICE: coursessor-frontend-service-europe

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Authenticate with Google Cloud
      id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
        
    - name: Configure docker for GCP
      run: gcloud auth configure-docker $LOCATION-docker.pkg.dev --quiet 
      
    - name: Park CLI setup
      id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v5.0.0
      
    - name: Build and push Docker image using Cloud Native Buildpacks
      run: |
        gcr.io/coursessor-380913/github.com/coursessor/coursessor
        pack build $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG --builder gcr.io/buildpacks/builder
        docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
        
    - id: "deploy"
      uses: "google-github-actions/deploy-cloudrun@v1"
      with:
        service: ${{ env.SERVICE }}
        image: "gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG"

    - name: "Use output"
      run: 'curl "${{ steps.deploy.outputs.url }}"'

