name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ./app
      run: npm install

    - name: Build Application
      working-directory: ./app
      run: npm run build

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '344.0.0'
        project_id: coursessor-380913
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      id: gcloud

    - name: Configure Docker
      uses: actions/setup-docker@v2

    - name: Build and push Docker image
      env:
        PROJECT_ID: coursessor-380913
        IMAGE_NAME: coursessor-image
        TAG_NAME: ${{ github.sha }}
      run: |
        echo ${{ secrets.GCP_CREDENTIALS }} > key.json
        gcloud auth activate-service-account --key-file=key.json
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME ./app
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME

    - name: Logout of Docker
      run: docker logout

    - name: Update Cloud Run service
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      with:
        image: gcr.io/coursessor-380913/coursessor-image:${{ github.sha }}
        service: coursessor-frontend-service-europe
        region: europe-west8
        platform: managed
        allow-unauthenticated: true
        service-account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ secrets.PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
