name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ./app
      run: npm install

    - name: Build Application
      working-directory: ./app
      run: npm run build

