name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - name: Install dependencies
      run: npm install --app
    - name: Build
      run: npm run build
