name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Change directory to app
      run: cd app
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
