name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ./app
      run: npm install

    - name: Build Application
      working-directory: ./app
      run: npm run build
      
    - name: Download pack
      run: curl -sSL https://github.com/buildpacks/pack/releases/latest/download/pack-linux.tgz | tar xzv pack

    - name: Move pack binary to system path
      run: sudo mv pack /usr/local/bin/pack
      
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: false
        file: ./Dockerfile
        buildargs: |
          APP_DIRECTORY=app
        tags: coursessor-image