name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: coursessor-380913
  REGION: europe-west8
  IMAGE_NAME: coursessor-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ./app
      run: npm install

    - name: Build Application
      working-directory: ./app
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build and push Docker image
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-credentials.json
        GOOGLE_CLOUD_PROJECT: ${{ env.PROJECT_ID }}
        GOOGLE_REGION: ${{ env.REGION }}
        PORT: 8080
      run: |
        docker build \
          --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --build-arg NODE_ENV=production \
          --build-arg PORT=${{ env.PORT }} \
          --build-arg APP_DIRECTORY=app \
          .

        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: GoogleCloudPlatform/github-actions/cloud-run@master
      with:
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        service_name: ${{ env.IMAGE_NAME }}
        region: ${{ env.REGION }}
        project_id: ${{ env.PROJECT_ID }}
        allow_unauthenticated: true
